[package]
name = "libkafka"
version = "0.1.0"
authors = ["grumbach <anselmega@gmail.com>"]
edition = "2018"

[lib]
name = "kafka"
crate-type = ["lib"]

[dependencies]
rdkafka = { version = "0", features = ["cmake-build"] }
thiserror = "1.0"
log = "0.4"
tokio = { version = "1.17", features = ["rt-multi-thread"], optional = true}

[dev-dependencies]
tokio = { version = "1.17", features = ["rt-multi-thread", "macros"]}
rand = "0"

[features]
default = []
kafka_debug = []
async = ["tokio"]
