[package]
name = "libkafka"
version = "0.1.0"
authors = ["grumbach <anselmega@gmail.com>"]
edition = "2018"

[lib]
name = "kafka"
crate-type = ["cdylib", "lib"]

[features]
python = ["pyo3"]

[dependencies]
rdkafka = { version = "0", features = ["cmake-build"] }
pyo3 = { optional = true, version = "0", features = ["extension-module"] }
thiserror = "1.0"

[dev-dependencies]
rand = "0"
